Disable NTLM test
It causes an exception because it seems that there's version incompatibility
between rack-ntlm and rack-ntlm-test-services. /cc @johncant

NoMethodError: undefined method `blank?' for nil:NilClass
	/home/nahi/.gem/ruby/2.2.0/gems/rack-ntlm-0.0.1/lib/rack/ntlm.rb:29:in `call'
	/home/nahi/.gem/ruby/2.2.0/gems/rack-1.5.2/lib/rack/content_length.rb:14:in `call'
	/home/nahi/.gem/ruby/2.2.0/gems/rack-1.5.2/lib/rack/showexceptions.rb:24:in `call'
	/home/nahi/.gem/ruby/2.2.0/gems/rack-1.5.2/lib/rack/handler/webrick.rb:60:in `service'
	test/test_auth.rb:53:in `block in setup_server'
	/usr/local/lib/ruby/2.2.0/webrick/httpservlet/prochandler.rb:38:in `call'
	/usr/local/lib/ruby/2.2.0/webrick/httpservlet/prochandler.rb:38:in `do_GET'
	/usr/local/lib/ruby/2.2.0/webrick/httpservlet/abstract.rb:106:in `service'
	/usr/local/lib/ruby/2.2.0/webrick/httpserver.rb:138:in `service'
	/usr/local/lib/ruby/2.2.0/webrick/httpserver.rb:94:in `run'
	/usr/local/lib/ruby/2.2.0/webrick/server.rb:295:in `block in start_thread'